[package]
name = "OpenRDX"
version = "0.1.0"
edition = "2024"
authors = ["Ilinaya"]

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
radius-rust = { version = "0.4.4", features = ["async-radius"] }
async-std = "1.12.0"
async-trait = "0.1"
futures = "0.3"
log = "0.4"
simple_logger = "5.0.0"
md4 = "0.10.1"
hmac = "0.12.1"
sha-1 = "0.10.1"
hex = "0.4.3"
